# nginx proxy address - http://172.17.0.1:8104

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  picoshare:
    image: picoshare/picoshare:latest
    container_name: picoshare-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - picoshare
    ports:
      - "8104:8104"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/picoshare:/config
      - ./volumes/data/picoshare:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8104"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  picoshare:
    external: false
